name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git dialog lsb-release binutils debootstrap

      - name: Clone Armbian Build
        run: git clone https://github.com/armbian/build.git

      - name: Copy customize-image.sh
        run: cp -r userpatches build/

      - name: Set file permissions
        run: |
          chmod +x build/userpatches/customize-image.sh
          chmod +x build/compile.sh

      - name: Build Armbian image
        run: |
          cd build
          ./compile.sh \
            BOARD=orangepizero \
            BRANCH=current \
            BUILD_DESKTOP=no \
            BUILD_MINIMAL=yes \
            KERNEL_CONFIGURE=no \
            RELEASE=focal \
            DEST_LANG="pt_BR.UTF-8" \
            SHARE_LOG=yes

      - name: Upload Armbian image
        uses: actions/upload-artifact@v3
        with:
          name: Armbian-Image
          path: build/output/images/

      - name: Get image name
        id: get_image_name
        run: |
          echo "::set-output name=image_name::$(ls build/output/images/ | grep .img)"

      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GH_TOKEN }}
